ln -s ../modulos/sucursal_asistencias
ln -s ../modulos/sucursal_clientes
ln -s ../modulos/sucursal_clientes_nuevo
ln -s ../modulos/sucursal_clientes_nuevo2
ln -s ../modulos/sucursal_codigo_barra
ln -s ../modulos/sucursal_consulta
ln -s ../modulos/sucursal_consulta2
ln -s ../modulos/sucursal_consulta.bak
ln -s ../modulos/sucursal_lanzamientos
ln -s ../modulos/sucursal_novedades
ln -s ../modulos/sucursal_pedidos
ln -s ../modulos/sucursal_reportes
ln -s ../modulos/sucursal_reportes_caja
ln -s ../modulos/sucursal_ventas
ln -s ../modulos/sucursal_ventas_dia
ln -s ../modulos/sucursal_ventas_dia_limit
ln -s ../modulos/sucursal_ventas_gremio
ln -s ../modulos/sucursal_ventas_nuevo
