<?php
//$array_articulos=array_articulos($id_articulos);

echo '<table border="1">';
    echo '<tr>';
        echo '<td>id</td>';
        echo '<td>'.$array_articulos["id"].'</td>';
    echo '</tr>';
    echo '<tr>';
        echo '<td>codigo_interno</td>';
        echo '<td>'.$array_articulos["codigo_interno"].'</td>';
    echo '</tr>';
    echo '<tr>';
        echo '<td>marca</td>';
        echo '<td>'.$array_articulos["marca"].'</td>';
    echo '</tr>';
    echo '<tr>';
        echo '<td>descripcion</td>';
        echo '<td>'.$array_articulos["descripcion"].'</td>';
    echo '</tr>';
    echo '<tr>';
        echo '<td>contenido</td>';
        echo '<td>'.$array_articulos["contenido"].'</td>';
    echo '</tr>';
    echo '<tr>';
        echo '<td>presentacion</td>';
        echo '<td>'.$array_articulos["presentacion"].'</td>';
    echo '</tr>';
    echo '<tr>';
        echo '<td>codigo_barra</td>';
        echo '<td>'.$array_articulos["codigo_barra"].'</td>';
    echo '</tr>';
    echo '<tr>';
        echo '<td>clasificacion</td>';
        echo '<td>'.$array_articulos["clasificacion"].'</td>';
    echo '</tr>';
    echo '<tr>';
        echo '<td>subclasificacion</td>';
        echo '<td>'.$array_articulos["subclasificacion"].'</td>';
    echo '</tr>';
    echo '<tr>';
        echo '<td>Stock</td>';
        echo '<td>'.$array_stock["stock"].'</td>';
    echo '</tr>';
    echo '<tr>';
        echo '<td>Ingreso</td>';
        echo '<td>'.$_POST["cantidad"].'</td>';
    echo '</tr>';
    echo '<tr>';
        echo '<td>Stock nuevo</td>';
        echo '<td>'.$stock_nuevo.'</td>';
    echo '</tr>';
        echo '<td>Minimo</td>';
        echo '<td>'.$array_stock["minimo"].'</td>';
    echo '</tr>';
    echo '<tr>';
        echo '<td>Maximo</td>';
        echo '<td>'.$array_stock["maximo"].'</td>';
    echo '</tr>';
  echo '</table>';  
?>